// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdFHtYuRMYwW1mYnIOY52s85ZZz26eYCc',
    appId: '1:600804380370:web:2102d30f33e1b149c7a70b',
    messagingSenderId: '600804380370',
    projectId: 'project-final-4beda',
    authDomain: 'project-final-4beda.firebaseapp.com',
    storageBucket: 'project-final-4beda.appspot.com',
    measurementId: 'G-BLFF6XX38H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFWANVB5ulInPJqQT4zu-1fHURC_B1WdM',
    appId: '1:600804380370:android:54fd15e4a863f9dec7a70b',
    messagingSenderId: '600804380370',
    projectId: 'project-final-4beda',
    storageBucket: 'project-final-4beda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp4URPWsKvFPExs4ff7iJk471e9llCZB4',
    appId: '1:600804380370:ios:d53e02dc947d564bc7a70b',
    messagingSenderId: '600804380370',
    projectId: 'project-final-4beda',
    storageBucket: 'project-final-4beda.appspot.com',
    androidClientId: '600804380370-83mj4asvuooj1gkp4esfkeg878of5lk2.apps.googleusercontent.com',
    iosClientId: '600804380370-l36bg50c0qv08rcq71701f97648spjc4.apps.googleusercontent.com',
    iosBundleId: 'com.flutterthailand.projectWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp4URPWsKvFPExs4ff7iJk471e9llCZB4',
    appId: '1:600804380370:ios:18bd8efa7a318d63c7a70b',
    messagingSenderId: '600804380370',
    projectId: 'project-final-4beda',
    storageBucket: 'project-final-4beda.appspot.com',
    androidClientId: '600804380370-83mj4asvuooj1gkp4esfkeg878of5lk2.apps.googleusercontent.com',
    iosClientId: '600804380370-354h3gtlq2ra5n2tu3dtnj68h09lem1h.apps.googleusercontent.com',
    iosBundleId: 'com.flutterthailand.projectWeb.RunnerTests',
  );
}
